### ISSUE TITLE
Persistent sorting of settlement list by "Turn Income" descending

### ISSUE THREAD

**Issue by Stache73** [FeralInteractive/romeremastered#4]
Is there a file I can edit myself, so that when I open the settlement list, the list always opens with the settlements sorted by "Turn Income" (descending from most income to least income) by default and so that it stays this way so it is sorted this way every time I open the settlement list? 

What file contains the instructions for sorting UI elements in settlements?

**Comment by esmithferal** [comment]
This isn't possible as that would need an engine change.
